export const API_KEY = "3131206a20851a466c1a22192ac3d9fb"
export const API_READ_ACCESS_TOKEN = "eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIzMTMxMjA2YTIwODUxYTQ2NmMxYTIyMTkyYWMzZDlmYiIsInN1YiI6IjY1YWFkYjM1MGM0YzE2MDBjZTdiYTU0NSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.n8EwuCbs7rWk7CIP27OK4S4Hn1cpLPECtrDwXtOjclI"
export const POPULAR_MOVIES_URL = "https://api.themoviedb.org/3/movie/popular"
export const SEARCH_COLLECTION_MOVIES_URL = "https://api.themoviedb.org/3/search/movie"
export const GET_A_MOVIE_URL = "https://api.themoviedb.org/3/movie"